version: '3.3'
services:
  alfresco:
    build: 
      context: ./alfresco_one
      args:
        - awsAccessKey=xxx
        - awsSecretKey=xxx
        - awsRegionName=eu-central-1
        - awsS3BucketName=alfresco-certificates
        - alfrescoRepoServer=104.199.19.121
        - alfrescoRepoPort=80
    env_file: .env
    ports:
      - "80:8080"
  alfresco-proxy:
    image: alfresco-proxy
    build:
      context: ./alfresco-proxy/alfresco-proxy
      dockerfile: Dockerfile
    depends_on:
      - ci-build
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5004
    ports:
      - "5100:5004"