version: '2'
services:
  alfresco:
    build: alfresco_one
    environment:
      ALF_HOSTNAME: "104.199.19.121"
      AWS_ACCESS_KEY_ID: "XXX"
      AWS_SECRET_ACCESS_KEY: "XXXX"
      AWS_REGION_NAME: "eu-central-1"
      AWS_S3_BUCKET_NAME: "alfresco-certificates"
    ports:
      - "80:8080"