#!/bin/bash

###
# Fix properties in alfresco-global.properties
###
sed -i 's:^[ \t]*alfresco.host[ \t]*=\([ \t]*.*\)$:alfresco.host='$ALF_HOSTNAME':' $ALF_PROPS_FILE
sed -i 's:^[ \t]*share.host[ \t]*=\([ \t]*.*\)$:share.host='$ALF_HOSTNAME':' $ALF_PROPS_FILE

# Start alfresco (exits immediately running the server as a daemon)
$ALFRESCO_HOME/alfresco.sh start

# Long running process that will keep the daemonised docker process alive
# and may be seen with 'docker logs [-f] alfresco' where alfresco is the name of the container.
tail -f $ALFRESCO_HOME/alfresco.log